const AllProducts = [
  {
    id: "pant1a",
    prodCat: "pant",
    prodImg: "/images/pants_pics/pant1_pic1.jpg",
    prodBrand: "MARC N SPENCER",
    color: "orange",
  },
  {
    id: "pant1b",
    prodCat: "pant",
    prodImg: "/images/pants_pics/pant1_pic2.jpg",
    prodBrand: "MARC N SPENCER",
    color: "orange",
  },
  {
    id: "pant2",
    prodCat: "pant",
    prodImg: "/images/pants_pics/pant2.jpg",
    prodBrand: "LEVIS",
    color: "blue",
  },
  {
    id: "pant3",
    prodCat: "pant",
    prodImg: "/images/pants_pics/pant3.jpg",
    prodBrand: "HRX",
    color: "black",
  },
  {
    id: "top1a",
    prodCat: "shirt",
    prodImg: "/images/tops_pics/top1_pic1.jpg",
    prodBrand: "G-STAR",
    color: "white",
  },
  {
    id: "top1b",
    prodCat: "shirt",
    prodImg: "/images/tops_pics/top1_pic2.jpg",
    prodBrand: "G-STAR",
    color: "white",
  },
  {
    id: "top2",
    prodCat: "shirt",
    prodImg: "/images/tops_pics/top2.jpg",
    prodBrand: "BLUEBERRY",
    color: "blue",
  },
  {
    id: "top3",
    prodCat: "shirt",
    prodImg: "/images/tops_pics/top3.jpg",
    prodBrand: "CHANNEL",
    color: "black",
  },
  {
    id: "shoe1a",
    prodCat: "shoe",
    prodImg: "/images/shoes_pics/shoe1_pic1.jpg",
    prodBrand: "ADIDAS",
    color: "pink",
  },
  {
    id: "shoe1b",
    prodCat: "shoe",
    prodImg: "/images/shoes_pics/shoe1_pic2.jpg",
    prodBrand: "ADIDAS",
    color: "pink",
  },
  {
    id: "shoe2",
    prodCat: "shoe",
    prodImg: "/images/shoes_pics/shoe2.jpg",
    prodBrand: "CHANNEL",
    color: "blue",
  },
  {
    id: "shoe3",
    prodCat: "shoe",
    prodImg: "/images/shoes_pics/shoe3.jpg",
    prodBrand: "LIVI",
    color: "pink",
  },
  {
    id: "purse1a",
    prodCat: "bag",
    prodImg: "/images/purse_pics/purse1_pic1.jpg",
    prodBrand: "GUCCI",
    color: "red",
  },
  {
    id: "purse1b",
    prodCat: "bag",
    prodImg: "/images/purse_pics/purse1_pic2.jpg",
    prodBrand: "GUCCI",
    color: "red",
  },
  {
    id: "purse2",
    prodCat: "bag",
    prodImg: "/images/purse_pics/purse2.jpg",
    prodBrand: "NAVI",
    color: "orange",
  },
  {
    id: "purse3",
    prodCat: "bag",
    prodImg: "/images/purse_pics/purse3.jpg",
    prodBrand: "NYKA",
    color: "blue",
  },
];

export default AllProducts;
